language: php
php:
  - '5.6'
  - '7.1'
before_script:
  - composer install
script:
  - vendor/bin/phpunit -d memory_limit=512M --colors --stop-on-error --exclude-group disabled -c tests/phpunit_travis.xml --stderr $@
